# .scrutinizer.yml
checks:
    php:
        code_rating: true
        duplication: true
    javascript: true

filter:
    paths: ['App/*']
    
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
        php: 7.0.8
    tests:
            override:
                -
                    command: 'phpunit --coverage-clover=clover.xml'
                    coverage:
                        file: 'clover.xml'
                        format: 'clover'
