# .scrutinizer.yml
checks:
    php:
        code_rating: true
        duplication: true
    javascript: true

filter:
    paths: ['src/*']
    
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
        php: 7.0.8
        mysql: 5.5
        memcached: true
        mongodb: true
    tests:
            override:
                -
                    command: '/usr/local/bin/phpunit --coverage-clover=clover.xml'
                    coverage:
                        file: 'clover.xml'
                        format: 'clover'

    project_setup:
            before:
                - composer require mongodb/mongodb
                - mysql -e "CREATE DATABASE test"
                - mysql -u root test < tests/database.sql
                - wget https://phar.phpunit.de/phpunit.phar
                - chmod +x phpunit.phar
                - sudo mv phpunit.phar /usr/local/bin/phpunit