# .scrutinizer.yml
checks:
    php: true
    javascript: true

filter:
    paths: ['src/*']
    
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
        php: 7.0.8
