language: php
php:
- 7.0
- 7.1
- hhvm

matrix:
  allow_failures:
  - php: 7.1
  - php: hhvm

services:
- mysql
- memcached  

before_script:
- if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
- mysql -e 'create database test;'
- mysql -u root test < tests/database.sql
- phpunit --self-update
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then composer require codeclimate/php-test-reporter --dev; fi
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then composer install; fi

script: 
- phpunit --coverage-clover build/logs/clover.xml

after_script:
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then CODECLIMATE_REPO_TOKEN="ea1f219277a5252d15c802943d472ee22ef87769366ea3f75ae28106dcaa8d76" vendor/bin/test-reporter; fi