language: php
php:
- 7.0
- 7.1
- nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then composer require codeclimate/php-test-reporter --dev; fi
- composer install

script: 
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then phpunit --coverage-clover build/logs/clover.xml; else phpunit; fi

after_script:
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then CODECLIMATE_REPO_TOKEN="ea1f219277a5252d15c802943d472ee22ef87769366ea3f75ae28106dcaa8d76" vendor/bin/test-reporter; fi
